sudo: false
language: c

matrix:
  include:
    - env: GHCVER=7.8.4 STACK_LTS=lts-2 STACK_TEMPLATE=stack-lts-2.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.8.4 ]
    - env: GHCVER=7.10.2 STACK_LTS=lts-3 STACK_TEMPLATE=stack-lts-3.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.2 ]
    - env: GHCVER=7.10.3 STACK_LTS=lts-5 STACK_TEMPLATE=stack-lts-5.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.3 ]
    - env: GHCVER=7.10.3 STACK_LTS=lts-6 STACK_TEMPLATE=stack-lts-6.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-7.10.3 ]
    - env: GHCVER=8.0.2 STACK_LTS=lts-8 STACK_TEMPLATE=stack-lts-8.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-8.0.2 ]
    - env: GHCVER=8.0.2 STACK_LTS=nightly STACK_TEMPLATE=stack-nightly.yaml
      addons:
        apt:
          sources: [ hvr-ghc ]
          packages: [ ghc-8.0.2 ]
  allow_failures:
    - env: GHCVER=8.0.2 STACK_LTS=nightly STACK_TEMPLATE=stack-nightly.yaml

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # stack searches .cabal file based on STACK_YAML directory.
  - m4 -D__RESOLVER__=$(curl -sL https://www.stackage.org/download/snapshots.json | jq '."'$STACK_LTS'"' -r) .travis/$STACK_TEMPLATE > stack.yaml

install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - travis_wait stack --no-terminal --skip-ghc-check test
  - cat .stack-work/logs/twitter-conduit-*-test.log

  # tests source distribution package
  - .travis/check-sdist.sh twitter-conduit

cache:
  directories:
    - ~/.stack

notifications:
  slack:
    secure: HUt3eZH5IBJXlgH1/ob+iMqaQRSloqT3VY0rMLmD7gOMpUFm3a5/XYejqD+hd7EYQRa/Z1YCpmIBe3RYGPt6TnNGvIFdcJFFO7lOs7Ooxp03yB5kAMw9eACv/FNJPd2aIjYdKGbSab4XY4s9wW0GewYv0FHrNFWj81Rhl8C4fGg=
